{% set name = "pyink" %}
{% set version = "23.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyink-{{ version }}.tar.gz
  sha256: cc940ec3b1c0f746c61e10f1e28a5b69a274da20843e14ee14fbb4130b3a4853

build:
  noarch: python
  entry_points:
    - pyink = pyink:patched_main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling >=1.8.0
    - hatch-vcs
    - pip
  run:
    - python >=3.7
    - click >=8.0.0
    - mypy_extensions >=0.4.3
    - packaging >=22.0
    - pathspec >=0.9.0
    - platformdirs >=2
    - tomli >=1.1.0
    - typed-ast >=1.4.2
    - typing-extensions >=3.10.0.0
    - black >=22.12.0

test:
  imports:
    - pyink
  commands:
    - pip check
    - pyink --help
  requires:
    - pip

about:
  home: https://github.com/google/pyink
  summary: Pyink is a python formatter, forked from Black with slightly different behavior.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
